name: 'GitHub Event Sync to Lark'
description: 'Sync GitHub events (PR, Issues, CI) to Lark group'
inputs:
  webhook_url:
    description: 'Lark group webhook URL'
    required: true
runs:
  using: 'node20'
  main: 'lib/index.js'
