module.exports = {
  'no-irregular-whitespace': ['error', { skipStrings: true, skipComments: true }],
  'no-var': 'error',
  'prefer-const': 'error',
  'no-undef': 'error',
  'no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
  'no-inner-declarations': ['error', 'both'],
  'no-self-assign': 'error',
  'no-array-constructor': 'error',
  'prefer-destructuring': ['warn', { object: true, array: false }],
  'no-sparse-arrays': 'error',
  'no-new-object': 'error',
  'object-shorthand': 'error',
  'no-empty-pattern': 'error',
  'dot-notation': 'error',
  'no-unsafe-optional-chaining': 'error',
  'constructor-super': 'error',
  'no-this-before-super': 'error',
  'no-useless-constructor': 'error',
  'getter-return': ['error', { allowImplicit: true }],
  'no-setter-return': 'error',
  'no-dupe-class-members': 'error',
  'no-class-assign': 'error',
  'no-async-promise-executor': 'error',
  'prefer-promise-reject-errors': 'error',
  'default-param-last': 'error',
  'no-func-assign': 'error',
  'no-unsafe-negation': 'error',
  'valid-typeof': 'error',
  'no-empty': 'error',
  'no-extra-bind': 'error',
  'no-prototype-builtins': 'error',
  'new-parens': 'error',
  'no-multi-str': 'error',
  'use-isnan': 'error',
  'no-loss-of-precision': 'error',
  'no-floating-decimal': 'error',
  'no-magic-numbers': [
    'warn',
    {
      ignoreArrayIndexes: true,
      ignoreDefaultValues: true,
      enforceConst: true,
      ignore: [0, 1, -1],
      ignoreClassFieldInitialValues: true,
    },
  ],
  'guard-for-in': 'warn',
  'for-direction': 'error',
  'no-unmodified-loop-condition': 'error',
  'no-unreachable': 'error',
  'no-unsafe-finally': 'error',
  'no-cond-assign': ['error', 'always'],
  'no-constant-condition': ['error', { checkLoops: false }],
  'no-dupe-else-if': 'error',
  'no-extra-boolean-cast': ['error', { enforceForLogicalOperands: true }],
  'no-useless-catch': 'error',
  'no-ex-assign': 'error',
  'no-throw-literal': 'error',
  'no-fallthrough': 'error',
  'default-case': 'error',
  'default-case-last': 'error',
  'no-case-declarations': 'error',
  eqeqeq: 'error',
  'no-compare-neg-zero': 'error',
  'no-invalid-regexp': 'error',
  'no-control-regex': 'error',
  'no-empty-character-class': 'error',
  'no-with': 'error',
  'no-eval': 'error',
  'no-implied-eval': 'error',
  'no-new-wrappers': 'error',
  'no-new-symbol': 'error',
  'no-global-assign': 'error',
  'no-obj-calls': 'error',
  'no-debugger': 'error',
  'no-caller': 'error',
  'no-implicit-coercion': ['error', { allow: ['!!'] }],
  camelcase: ['error', { properties: 'never', allow: ['^UNSAFE_'] }],
  'no-import-assign': 'error',
  'no-duplicate-case': 'error',
  'no-empty-function': 'error',
  'prefer-rest-params': 'error',
};
