#!/bin/bash
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.

# Invoke the "rush prettier" custom command to reformat files whenever they
# are committed. The command is defined in common/config/rush/command-line.json
# and uses the "rush-lint-staged" autoinstaller.

# Force to update codeowners file if packasge.json changed.

# block unresolved conflict; https://git-scm.com/docs/git-diff

if [ "$PRE_LINT" != "1" ]; then
  node common/scripts/install-run-rush.js -q lint-staged || exit $?
fi
