# should be optimize as increment build & test
name: CI@main
on:
  push:
    branches: ['main']
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        include:
          - NodeVersion: 20.9.x
            NodeVersionDisplayName: 20
            OS: ubuntu-latest
    name: Node.js v${{ matrix.NodeVersionDisplayName }} (${{ matrix.OS }})
    runs-on: ${{ matrix.OS }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Config Git User
        # should be turn to ci user
        run: |
          git config --local user.name "tecvan"
          git config --local user.email "fanwenjie.fe@bytedance.com"

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.NodeVersion }}

      - name: Install Dependencies
        run: node common/scripts/install-run-rush.js install

      - name: Build all
        run: node common/scripts/install-run-rush.js build --verbose

      - name: Test:cov all
        run: node common/scripts/install-run-rush.js test:cov --verbose

      - name: Upload coverage reports
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true

      - name: Lint all
        run: node common/scripts/install-run-rush.js lint --verbose
