# event list: https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows
on:
  issues:
    types: [opened, closed]
  pull_request:
    types: [opened, closed]
    branches: ['main']
  workflow_run:
    workflows: ['CI']
    types: [completed]

jobs:
  event_sync_job:
    runs-on: ubuntu-latest
    name: A job to sync events to Lark
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Event sync action step
        uses: ./.github/actions/event-sync
        id: event_sync
        with:
          lark_webhook_url: ${{ secrets.LARK_WEBHOOK_URL }}
